INSERT INTO `tb_banco` (`NU_BANCO`, `NO_BANCO`, `URL_BANCO`) VALUES
    (246, 'Banco ABC Brasil S.A', 'www.abcbrasil.com.br'),
    (25, 'Banco Alfa S.A', 'www.bancoalfa.com.br'),
    (641, 'Banco Alvorada S.A', null),
    (29, 'Banco Banerj S.A', 'www.banerj.com.br'),
    (740, 'Banco Barclays S.A', 'www.barclays.com'),
    (107, 'Banco BBM S.A', 'www.bbmbank.com.br'),
    (31, 'Banco Beg S.A', 'www.itau.com.br'),
    (739, 'Banco BGN S.A', 'www.bgn.com.br'),
    (96, 'Banco BM&F de Serviços de Liquidação e Custódia S.A', 'www.bmf.com.br'),
    (318, 'Banco BMG S.A', 'www.bancobmg.com.br'),
    (752, 'Banco BNP Paribas Brasil S.A', 'www.bnpparibas.com.br'),
    (248, 'Banco Boavista Interatlântico S.A', null),
    (218, 'Banco Bonsucesso S.A', 'www.bancobonsucesso.com.br'),
    (65, 'Banco Bracce S.A', 'www.bancobracce.com.br'),
    (36, 'Banco Bradesco BBI S.A', null),
    (204, 'Banco Bradesco Cartões S.A', 'www.iamex.com.br'),
    (394, 'Banco Bradesco Financiamentos S.A', 'www.bmc.com.br'),
    (237, 'Banco Bradesco S.A', 'www.bradesco.com.br'),
    (225, 'Banco Brascan S.A', 'www.bancobrascan.com.br'),
    (208, 'Banco BTG Pactual S.A', 'www.pactual.com.br'),
    (44, 'Banco BVA S.A', 'www.bancobva.com.br'),
    (263, 'Banco Cacique S.A', 'www.bancocacique.com.br'),
    (473, 'Banco Caixa Geral - Brasil S.A', null),
    (40, 'Banco Cargill S.A', 'www.bancocargill.com.br'),
    (745, 'Banco Citibank S.A', 'www.citibank.com.br'),
    (215, 'Banco Comercial e de Investimento Sudameris S.A', 'www.sudameris.com.br'),
    (756, 'Banco Cooperativo do Brasil S.A. - BANCOOB', 'www.bancoob.com.br'),
    (748, 'Banco Cooperativo Sicredi S.A', 'www.sicredi.com.br'),
    (222, 'Banco Credit Agricole Brasil S.A', 'www.calyon.com.br'),
    (505, 'Banco Credit Suisse (Brasil) S.A', 'www.csfb.com'),
    (229, 'Banco Cruzeiro do Sul S.A', 'www.bcsul.com.br'),
    (3, 'Banco da Amazônia S.A', 'www.bancoamazonia.com.br'),
    (083-3, 'Banco da China Brasil S.A', null),
    (707, 'Banco Daycoval S.A', 'www.daycoval.com.br'),
    (24, 'Banco de Pernambuco S.A. - BANDEPE', 'www.bandepe.com.br'),
    (456, 'Banco de Tokyo-Mitsubishi UFJ Brasil S.A', 'www.btm.com.br'),
    (214, 'Banco Dibens S.A', 'www.bancodibens.com.br'),
    (1, 'Banco do Brasil S.A', 'www.bb.com.br'),
    (47, 'Banco do Estado de Sergipe S.A', 'www.banese.com.br'),
    (37, 'Banco do Estado do Pará S.A', 'www.banparanet.com.br'),
    (41, 'Banco do Estado do Rio Grande do Sul S.A', 'www.banrisul.com.br'),
    (4, 'Banco do Nordeste do Brasil S.A', 'www.banconordeste.gov.br'),
    (265, 'Banco Fator S.A', 'www.bancofator.com.br'),
    (224, 'Banco Fibra S.A', 'www.bancofibra.com.br'),
    (626, 'Banco Ficsa S.A', 'www.ficsa.com.br'),
    (394, 'Banco Finasa BMC S.A', 'www.bmc.com.br'),
    (233, 'Banco GE Capital S.A', 'www.ge.com.br'),
    (612, 'Banco Guanabara S.A', 'www.bcoguan.com.br'),
    (63, 'Banco Ibi S.A. Banco Múltiplo', 'www.ibi.com.br'),
    (604, 'Banco Industrial do Brasil S.A', 'www.bancoindustrial.com.br'),
    (320, 'Banco Industrial e Comercial S.A', 'www.bicbanco.com.br'),
    (653, 'Banco Indusval S.A', 'www.indusval.com.br'),
    (249, 'Banco Investcred Unibanco S.A', null),
    (184, 'Banco Itaú BBA S.A', 'www.itaubba.com.br'),
    (479, 'Banco ItaúBank S.A', 'www.itaubank.com.br'),
    (376, 'Banco J. P. Morgan S.A', 'www.jpmorgan.com'),
    (74, 'Banco J. Safra S.A', 'www.jsafra.com.br'),
    (79, 'Banco JBS S.A', 'www.bancojbs.com.br'),
    (217, 'Banco John Deere S.A', 'www.johndeere.com.br'),
    (600, 'Banco Luso Brasileiro S.A', 'www.lusobrasileiro.com.br'),
    (389, 'Banco Mercantil do Brasil S.A', 'www.mercantil.com.br'),
    (746, 'Banco Modal S.A', 'www.bancomodal.com.br'),
    (45, 'Banco Opportunity S.A', 'www.opportunity.com.br'),
    (623, 'Banco Panamericano S.A', 'www.panamericano.com.br'),
    (611, 'Banco Paulista S.A', 'www.bancopaulista.com.br'),
    (643, 'Banco Pine S.A', 'www.bancopine.com.br'),
    (638, 'Banco Prosper S.A', 'www.bancoprosper.com.br'),
    (747, 'Banco Rabobank International Brasil S.A', 'www.rabobank.com.br'),
    (356, 'Banco Real S.A', 'www.bancoreal.com.br'),
    (633, 'Banco Rendimento S.A', 'www.rendimento.com.br'),
    (72, 'Banco Rural Mais S.A', 'www.rural.com.br'),
    (453, 'Banco Rural S.A', 'www.rural.com.br'),
    (422, 'Banco Safra S.A', 'www.safra.com.br'),
    (33, 'Banco Santander (Brasil) S.A', 'www.santander.com.br'),
    (250, 'Banco Schahin S.A', 'www.bancoschahin.com.br'),
    (749, 'Banco Simples S.A', 'www.bancosimples.com.br'),
    (366, 'Banco Société Générale Brasil S.A', 'www.sgbrasil.com.br'),
    (637, 'Banco Sofisa S.A', 'www.sofisa.com.br'),
    (12, 'Banco Standard de Investimentos S.A', 'www.standardbank.com'),
    (464, 'Banco Sumitomo Mitsui Brasileiro S.A', null),
    (082-5, 'Banco Topázio S.A', 'www.bancotopazio.com.br'),
    (634, 'Banco Triângulo S.A', 'www.tribanco.com.br'),
    (655, 'Banco Votorantim S.A', 'www.bancovotorantim.com.br'),
    (610, 'Banco VR S.A', 'www.vr.com.br'),
    (370, 'Banco WestLB do Brasil S.A', 'www.westlb.com.br'),
    (21, 'BANESTES S.A. Banco do Estado do Espírito Santo', 'www.banestes.com.br'),
    (719, 'Banif-Banco Internacional do Funchal (Brasil)S.A', 'www.banif.com.br'),
    (755, 'Bank of America Merrill Lynch Banco Múltiplo S.A', 'www.ml.com'),
    (73, 'BB Banco Popular do Brasil S.A', 'www.bancopopulardobrasil.com.br'),
    (78, 'BES Investimento do Brasil S.A.-Banco de Investimento', 'www.besinvestimento.com.br'),
    (69, 'BPN Brasil Banco Múltiplo S.A', 'www.bpnbrasil.com.br'),
    (70, 'BRB - Banco de Brasília S.A', 'www.brb.com.br'),
    (104, 'Caixa Econômica Federal', 'www.caixa.gov.br'),
    (477, 'Citibank N.A', 'www.citibank.com/brasil'),
    (081-7, 'Concórdia Banco S.A', 'www.concordiabanco.com'),
    (487, 'Deutsche Bank S.A. - Banco Alemão', 'www.deutsche-bank.com.br'),
    (751, 'Dresdner Bank Brasil S.A. - Banco Múltiplo', 'www.dkib.com.br'),
    (64, 'Goldman Sachs do Brasil Banco Múltiplo S.A', 'www.goldmansachs.com'),
    (62, 'Hipercard Banco Múltiplo S.A', 'www.hipercard.com.br'),
    (399, 'HSBC Bank Brasil S.A. - Banco Múltiplo', 'www.hsbc.com.br'),
    (492, 'ING Bank N.V', 'www.ing.com'),
    (652, 'Itaú Unibanco Holding S.A', 'www.itau.com.br'),
    (341, 'Itaú Unibanco S.A', 'www.itau.com.br'),
    (488, 'JPMorgan Chase Bank', 'www.jpmorganchase.com'),
    (409, 'UNIBANCO - União de Bancos Brasileiros S.A', 'www.unibanco.com.br'),
    (230, 'Unicard Banco Múltiplo S.A', 'www.unicard.com.br');