SELECT PCP_OP.CO_NUM                              AS ORD_CODIGO
    , PCP_OP.CO_ITEM                              AS ORD_ITEM
	  , PCP_OP.CO_SEQUENCIA                         AS ORD_SEQUEN
    , CONCAT(PCP_OP.CO_NUM, PCP_OP.CO_ITEM, PCP_OP.CO_SEQUENCIA) AS ORD_OP
    , (PCP_OP.QTD_PRODUTO - PCP_OP.QTD_PRODUZIDA) AS ORD_QUANT
	  , PCP_PRODUTO.CO_PRODUTO                      AS PCT_CODIGO
	  , TRIM(PCP_PRODUTO.CO_INT_PRODUTO)            AS PCT_CODINT
	  , TRIM(PCP_PRODUTO.DS_PRODUTO)                AS PCT_DESC
	  , TRIM(PCP_COR.DS_COR)                        AS PCT_COR
	  , TRIM(PCP_PRODUTO.NU_PESO)                   AS PCT_PESO
FROM tb_pcp_op PCP_OP

    INNER JOIN tb_pcp_produto PCP_PRODUTO
        ON PCP_OP.CO_PRODUTO = PCP_PRODUTO.CO_PRODUTO
	      AND PCP_PRODUTO.TP_PRODUTO IN ('PT','PF')

    LEFT JOIN tb_pcp_cor PCP_COR
	      ON PCP_PRODUTO.CO_COR = PCP_COR.CO_COR

WHERE PCP_OP.CO_NUM = '093171'
AND TRIM(PCP_OP.DT_FIM) = ''